language: php
php:
- 5.4
- 5.5
env:
  global:
  - secure: dVSnSGNBj1sEoABlZTVAmIcx7OSQsG7TZ4PD6n+sl5JhOfMsayfs4WBLYF2WLAIzRnPYjzftE2qtPaaYeRmMICr5r+aa1h5hbsDrAwN7LTpHu19B1hxE3KJrmGirU0e/7WGIEGixJYpvl1RLXnw83qdG/Y/fUilMHbwMWXLy2ns=
before_script:
- curl -s http://getcomposer.org/installer | php -- --quiet
- php composer.phar install --dev
script: ':'
after_success: ./post-build.sh
